language: node_js

before_script:
  - 'if [ "$WEBPACK_VERSION" ]; then npm install webpack@$WEBPACK_VERSION; fi'
  - npm install node-sass sass-extract

node_js:
  - "10"

env:
  - WEBPACK_VERSION=^4
  - WEBPACK_VERSION=^5